program: basic_blocks/scaffoldings.py
method: random
name: assignment1-optimizer-lr
description: sweep optimizer and batchsize hyperparameters betas
metric:
  goal: minimize
  name: Loss/train
parameters:
  batch_size:
    values: [32, 64, 128, 256]
  max_learning_rate:
    values: [1e-4, 3e-4, 5e-4, 1e-3, 1e-2, ]
  min_lr_ratio:
    values: [0.01, 0.05, 0.1, 0.5]
  warmup_iters:
    values: [500, 1000, 2000, 3000, 4000, 5000]
  weight_decay:
    values: [0.0, 0.01, 0.05, 0.1]
  beta1:
    values: [0.9, 0.85, 0.95]
  beta2:
    values: [0.95, 0.98, 0.99, 0.999]
  
  theta:
    values: [null, 10000]
  norm_type:
    values: ["no-norm", "pre-norm", "post-norm"]
  activation_type:
    values: ["SwiGLU", "SiLU_FFN"]
  